extends Control

@export_multiline var introLines: PackedStringArray = ["URGENT 
MESSAGE TOWARDS PRIVATE JIN WANGFENG", 
"FROM COMMAND REPRESENTING THE 19TH ENFORCEMENT DIVISION OF TENTOPICHAL PHAMARCY CO."]

@export_multiline var ending1Lines: PackedStringArray = ["STATUS UPDATE ON JIN WANGFENG", 
"JIN WANGFENG ACCORDING TO LIFE SCANNERS, HAS BEEN KILLED", "THE TENTOPICHAL PHAMARCY CO
SENDS THEIR REGARDS FOR THIS TERRIBLE LOSS OF LIFE", "DEDUCTION PENALTY TOWARDS 
JIN WANGFENG: $1042.10"]
@export_multiline var ending2Lines: PackedStringArray = ["STATUS UPDATE ON JIN WANGFENG", 
"JIN WANGFENG HAS BEEN FOUND ALIVE ACCOMPANYING THE SURVIVOR", "THE TENTOPICHAL PHAMARCY CO
CONGRATULATES HIS SUCCESS WITH THE MISSION", "DEDUCTION PENALTY TOWARDS 
JIN WANGFENG: $1042.10"]
@export_multiline var ending3Lines: PackedStringArray = ["STATUS UPDATE ON JIN WANGFENG", 
"JIN WANGFENG ACCORDING TO LIFE SCANNERS, HAS BEEN KILLED", "THE TENTOPICHAL PHAMARCY CO
SENDS THEIR REGARDS FOR THIS TERRIBLE LOSS OF LIFE", "DEDUCTION PENALTY TOWARDS 
JIN WANGFENG: $1042.10"]
@export_multiline var ending4Lines: PackedStringArray = ["STATUS UPDATE ON JIN WANGFENG", 
"JIN WANGFENG ACCORDING TO LIFE SCANNERS, HAS BEEN KILLED", "THE TENTOPICHAL PHAMARCY CO
SENDS THEIR REGARDS FOR THIS TERRIBLE LOSS OF LIFE", "DEDUCTION PENALTY TOWARDS 
JIN WANGFENG: $1042.10"]
@export_multiline var ending5Lines: PackedStringArray = ["STATUS UPDATE ON JIN WANGFENG", 
"JIN WANGFENG ACCORDING TO LIFE SCANNERS, HAS BEEN KILLED", "THE TENTOPICHAL PHAMARCY CO
SENDS THEIR REGARDS FOR THIS TERRIBLE LOSS OF LIFE", "DEDUCTION PENALTY TOWARDS 
JIN WANGFENG: $1042.10"]

# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
